version: 0.1
phases:
    install:
        commands:
        - npm install
        - npm i nodemon
        - npm install -g nodemon
        # - npm install -g vite
        # - npm install --save-dev vite
        # - npm install -g express
        - cd packages
        # - cd ecommerce
        # - npm install vite
        # - npm install
        # - cd ..
        - cd backend-items
        - npm install express
        - npm install       
        - cd ..
        - cd backend-history
        - npm install express
        - npm install
        - cd ..
        - cd ..
        - npx lerna run dev --stream --parallel
        - aws s3 cp build s3://$S3_BUCKET --recursive --exclude 'index.html'
        - aws s3 cp build/index.html s3://$S3_BUCKET